import os
import warnings
from typing import Dict

# The specialized libraries (rdkit, cclib, parmed) are imported lazily inside
# each backend, not up here: each format only needs one of them, and requiring
# all three at once would break, for example, analyzing a PDB in an
# environment where parmed failed to compile (typical on Windows without
# Visual C++ Build Tools) even though rdkit is available.

class HybridizationAnalyzer:
    """
    Main class acting as a Factory to analyze the hybridization of carbon
    atoms depending on the input file's format.

    `get_carbon_hybridizations()` is the structured API: it returns a
    dictionary {atom_index: 'SP'|'SP2'|'SP3'|...} indexed the same way as the
    source file, so another module (e.g. penindex.core) can align those
    indices with its own topology's when both are loaded from the same file.
    """

    # Mapping of common force-field atom types (GAFF, ff14SB, OPLS) to
    # hybridization. Simplified: for production use, extend this table per force field.
    TYPE_TO_HYB = {
        'CT': 'SP3', 'c3': 'SP3', 'CX': 'SP3',  # Aliphatic
        'C': 'SP2', 'CA': 'SP2', 'c2': 'SP2', 'ca': 'SP2',  # Trigonal/Aromatic
        'c1': 'SP', 'cg': 'SP',  # Linear
    }

    def __init__(self, file_path):
        self.file_path = file_path
        self.extension = os.path.splitext(file_path)[1].lower()

    def get_carbon_hybridizations(self) -> Dict[int, str]:
        """Main routing method based on the file extension.
        Returns {atom_index: hybridization} for every carbon atom."""
        if not os.path.exists(self.file_path):
            raise FileNotFoundError(f"File not found: {self.file_path}")

        if self.extension == '.xyz':
            return self._hybridizations_from_xyz()
        elif self.extension in ['.log', '.out']:
            return self._hybridizations_from_gaussian()
        elif self.extension == '.pdb':
            return self._hybridizations_from_pdb()
        elif self.extension in ['.prmtop', '.top']:
            return self._hybridizations_from_topology()
        else:
            warnings.warn(f"Unsupported format for hybridization detection: {self.extension}")
            return {}

    def analyze(self):
        """Convenience method for command-line use: prints a human-readable
        summary instead of returning the structured dictionary."""
        print(f"--- Analyzing: {os.path.basename(self.file_path)} ---")
        hyb_map = self.get_carbon_hybridizations()
        if not hyb_map:
            print("No carbons detected, or the format is not supported.")
            return

        for idx, hyb in list(hyb_map.items())[:10]:
            print(f"Carbon ID {idx}: {hyb}")
        if len(hyb_map) > 10:
            print(f"... and {len(hyb_map) - 10} more carbons.")

    def _hybridizations_from_xyz(self) -> Dict[int, str]:
        """Case 1: XYZ file. Uses RDKit to infer bonds from geometry."""
        try:
            from rdkit import Chem
            from rdkit.Chem import rdDetermineBonds
            raw_mol = Chem.MolFromXYZFile(self.file_path)
            # RDKit's C++ engine perceives connectivity and bond orders (optimized O(N))
            rdDetermineBonds.DetermineConnectivity(raw_mol)
            rdDetermineBonds.DetermineBondOrders(raw_mol)
            return self._hyb_map_from_rdkit_mol(raw_mol)
        except Exception as e:
            warnings.warn(f"Error processing XYZ with RDKit: {e}")
            return {}

    def _hybridizations_from_gaussian(self) -> Dict[int, str]:
        """Case 2: Gaussian output. Extracts the optimized geometry with cclib
        and uses RDKit to infer connectivity and hybridization from it.

        NOTE: if the file includes an NBO block, this method does not exploit
        it yet (the NBO format is very verbose); it falls straight through to
        the geometric path via cclib + RDKit, which is valid for any Gaussian
        output with an optimized geometry.
        """
        print("[INFO] Extracting optimized geometry with cclib...")
        try:
            import cclib
            from rdkit import Chem
            from rdkit.Chem import rdDetermineBonds

            data = cclib.io.ccread(self.file_path)
            last_coords = data.atomcoords[-1]
            atomic_numbers = data.atomnos

            xyz_block = f"{len(atomic_numbers)}\nGenerated by cclib\n"
            for z, coord in zip(atomic_numbers, last_coords):
                symbol = Chem.GetPeriodicTable().GetElementSymbol(int(z))
                xyz_block += f"{symbol} {coord[0]:.5f} {coord[1]:.5f} {coord[2]:.5f}\n"

            raw_mol = Chem.MolFromXYZBlock(xyz_block)
            rdDetermineBonds.DetermineConnectivity(raw_mol)
            rdDetermineBonds.DetermineBondOrders(raw_mol)
            return self._hyb_map_from_rdkit_mol(raw_mol)
        except Exception as e:
            warnings.warn(f"Error processing Gaussian output: {e}")
            return {}

    def _hybridizations_from_pdb(self) -> Dict[int, str]:
        """Case 3: PDB file. RDKit will read the CONECT records if present, or
        compute them from interatomic distances otherwise. The returned atom
        index matches the order of the ATOM/HETATM records in the file, the
        same way MDAnalysis does when loading the same PDB as a topology."""
        try:
            from rdkit import Chem
            mol = Chem.MolFromPDBFile(self.file_path, removeHs=False)
            if mol is None:
                warnings.warn("RDKit could not process the PDB (possibly not standardized).")
                return {}
            return self._hyb_map_from_rdkit_mol(mol)
        except Exception as e:
            warnings.warn(f"Error processing PDB: {e}")
            return {}

    def _hybridizations_from_topology(self) -> Dict[int, str]:
        """Case 4: AMBER/GROMACS topologies via ParmEd. Hybridization is
        inferred from the force-field atom type (simplified lookup table),
        not from geometric perception."""
        try:
            import parmed as pmd
            struct = pmd.load_file(self.file_path)
            hyb_map = {}
            for atom in struct.atoms:
                if atom.atomic_number == 6:  # Carbon
                    hyb_map[atom.idx] = self.TYPE_TO_HYB.get(atom.type, "UNKNOWN")
            return hyb_map
        except Exception as e:
            warnings.warn(f"Error processing topology: {e}")
            return {}

    @staticmethod
    def _hyb_map_from_rdkit_mol(mol) -> Dict[int, str]:
        """Helper function: builds {atom_index: hybridization} for every
        carbon of an already-sanitized RDKit Mol."""
        hyb_map = {}
        for atom in mol.GetAtoms():
            if atom.GetAtomicNum() == 6:
                hyb_str = str(atom.GetHybridization()).replace("HybridizationType.", "")
                hyb_map[atom.GetIdx()] = hyb_str
        return hyb_map
